### ISSUE TITLE
Error in spigot server gui when using /add-toy command

### ISSUE THREAD

**Issue by KillMeWithMemes** [Cyloci/ButtplugMc#1]
org.bukkit.command.CommandException: Unhandled exception executing command 'add-toy' in plugin ButtplugMc v0.0.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at com.psiloclast.buttplugmc.commands.AddToyCommand.connectButtplug(AddToyCommand.java:68) ~[?:?]
	at com.psiloclast.buttplugmc.commands.AddToyCommand.handleCommand(AddToyCommand.java:38) ~[?:?]
	at com.psiloclast.utils.Plugin.onCommand(Plugin.java:25) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.InvalidProtocolBufferException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.psiloclast.buttplugmc.commands.AddToyCommand.connectButtplug(AddToyCommand.java:68) ~[?:?]
	at com.psiloclast.buttplugmc.commands.AddToyCommand.handleCommand(AddToyCommand.java:38) ~[?:?]
	at com.psiloclast.utils.Plugin.onCommand(Plugin.java:25) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	... 19 more

**Comment by Cyloci** [comment]
Thanks so much for the Bug Report! I have seen this error once before, so this now confirms it as an issue.

Would you mind posting your exact Java version, your Operating System and architecture.

Thanks!

**Comment by KillMeWithMemes** [comment]
Java Version 8 Update 311 (build 1.8.0_311-b11)
Windows 10 Home, 64-bit Operating System
AMD Ryzen 5 3600 6-Core Processor 3.59 GHz
Not sure what else architecture might entail.

**Comment by Cyloci** [comment]
Okay thanks!

Okay so just adding the other report here for ease of access

Same error with the following machine
```
Windows 10 x64
Java version, 16.0.1
```

However another user reported this plugin worked with both their machines:
```
Windows Laptop
Intel i5 CPU
```

```
Windows AMD Desktop
```

As of now, I have no idea what is causing this issue. I thought it was a processor issue, but no. There must something quirky with my build process. Something about the protobufs from the Buttplug library...

I will have more time to look into this issue in a few weeks!

**Comment by KillMeWithMemes** [comment]
Any update?

**Comment by Cyloci** [comment]
Hey @KillMeWithMemes could you try this version?
[ButtplugMc-0.0.1.jar.zip](https://github.com/Cyloci/ButtplugMc/files/7930156/ButtplugMc-0.0.1.jar.zip)

**Comment by KillMeWithMemes** [comment]
"An internal error occurred while attempting to perform this command"
[00:00:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'add-toy' in plugin ButtplugMc v0.0.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at com.psiloclast.buttplugmc.commands.AddToyCommand.connectButtplug(AddToyCommand.java:73) ~[?:?]
	at com.psiloclast.buttplugmc.commands.AddToyCommand.handleCommand(AddToyCommand.java:40) ~[?:?]
	at com.psiloclast.utils.Plugin.onCommand(Plugin.java:25) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.InvalidProtocolBufferException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.psiloclast.buttplugmc.commands.AddToyCommand.connectButtplug(AddToyCommand.java:73) ~[?:?]
	at com.psiloclast.buttplugmc.commands.AddToyCommand.handleCommand(AddToyCommand.java:40) ~[?:?]
	at com.psiloclast.utils.Plugin.onCommand(Plugin.java:25) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	... 19 more
[00:00:14 WARN]: Can't keep up! Is the server overloaded? Running 15612ms or 312 ticks behind

**Comment by Cyloci** [comment]
[ButtplugMc-0.0.2.jar.zip](https://github.com/Cyloci/ButtplugMc/files/7945267/ButtplugMc-0.0.2.jar.zip)
Could you try this one, with a fresh 1.18.1 MC server? Make sure you have CommandAPI installed too.

**Comment by KillMeWithMemes** [comment]
Okay so now the command works.
I get "Searching for toys..." 5 times in a row and then "Couldn't find any toys."

**Comment by Cyloci** [comment]
Okay brilliant! This should mean the plugin is working correctly. I will push up a new release with this fix soon.

If it can't find any toys, it might mean something is going on with your Intiface setup. Try connecting to Intiface here: https://playground.buttplug.world/ and then try searching for your toy.

If the playground *can't* find your toy, make sure your toy is not connected to any other devices, like your phone (I usually turn bluetooth off on all other devices, as they try to steal the toy's connection). Also, some Operating Systems are currently not supported on Intiface yet, (like MacOS Monterrey) so, instead, I have found more success using the Lovense Connect app on my phone. Make sure to enable the Lovense Connect option in the Intiface desktop UI. Sometimes turning the toy off and on again can help too.

If the playground *can* find your toy, you can try turning the Intiface server off and on again, restarting the MC server, and turning the tou off and on again. Something might have just gone weird when setting things up. You shouldn't need to restart things again and it should connect.

If things still go wrong after trying this (a.k.a you can connect to the playground, but not to ButtplugMC), it might imply an issue specific to this plugin. Being unable to find the devices first time, or having to restart the server is not ideal user experience, so I would consider this a bug.

I'm going to close this issue, as this specific bug seems to have been solved for all affected user's machines. But if toy searching issues persist, please do make a new issue and we can see what we can do. :)
